services:
  postgres:
    container_name: social-media-postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data outside the container
    restart: unless-stopped # Restart unless explicitly stopped

volumes:
  postgres-data: # Named volume for persisting PostgreSQL data (so that we can swap between them)
